## <font color = "brown"> Importing Libraries </font>

In [3]:
import pandas as pd
import numpy as np
import warnings as wn

wn.filterwarnings("ignore")

## <font color = "brown"> Load Data </font>

In [21]:
df = pd.read_excel("data.xlsx")
df = df.set_index("Time")

In [22]:
df

                     Price  Demand
Time
2018-01-01 00:00:00  90.43    4599
2018-01-01 00:30:00  92.46    4398
2018-01-01 01:00:00  87.62    4238
2018-01-01 01:30:00  73.08    4112
2018-01-01 02:00:00  70.18    3956
...                    ...     ...
2021-08-14 22:00:00  49.93    5492
2021-08-14 22:30:00  62.86    5344
2021-08-14 23:00:00  32.26    5204
2021-08-14 23:30:00  25.10    5268
2021-08-15 00:00:00   8.73    5244

[63457 rows x 2 columns]

## <font color = "brown"> Preprocessing </font>

In [8]:
# Input your obtained optimal lag
optimal_lag = 100

# Extract column names
features = df.columns

# Loop through each lags
for i in range(1, optimal_lag + 1):
    
    # Loop through each features
    for j in features:
        
        # Add lag i of feature j in the dataframe
        df[f"{j}_Lag_{i}"] = df[j].shift(i)
        
# Remove all missing values
df = df.dropna()

In [10]:
# Insert an intercept column with value of 1 throughout
df.insert(0, "Intercept", 1)

In [11]:
# Extract predicted variables
y_price = df["Price"]
y_demand = df["Demand"]
df = df.drop(["Price", "Demand"], axis = 1)
df

,Intercept,Price_Lag_1,Demand_Lag_1,Price_Lag_2,Demand_Lag_2,Price_Lag_3,Demand_Lag_3,Price_Lag_4,Demand_Lag_4,Price_Lag_5,...,Price_Lag_96,Demand_Lag_96,Price_Lag_97,Demand_Lag_97,Price_Lag_98,Demand_Lag_98,Price_Lag_99,Demand_Lag_99,Price_Lag_100,Demand_Lag_100
Time,,,,,,,,,,,,,,,,,,,,,
2018-01-03 02:00:00,1,46.83,4185.0,55.01,4296.0,59.33,4444.0,66.02,4624.0,65.81,...,70.18,3956.0,73.08,4112.0,87.62,4238.0,92.46,4398.0,90.43,4599.0
2018-01-03 02:30:00,1,46.92,4061.0,46.83,4185.0,55.01,4296.0,59.33,4444.0,66.02,...,67.43,3833.0,70.18,3956.0,73.08,4112.0,87.62,4238.0,92.46,4398.0
2018-01-03 03:00:00,1,49.74,3960.0,46.92,4061.0,46.83,4185.0,55.01,4296.0,59.33,...,66.31,3749.0,67.43,3833.0,70.18,3956.0,73.08,4112.0,87.62,4238.0
2018-01-03 03:30:00,1,49.37,3884.0,49.74,3960.0,46.92,4061.0,46.83,4185.0,55.01,...,67.72,3702.0,66.31,3749.0,67.43,3833.0,70.18,3956.0,73.08,4112.0
2018-01-03 04:00:00,1,50.99,3879.0,49.37,3884.0,49.74,3960.0,46.92,4061.0,46.83,...,65.50,3688.0,67.72,3702.0,66.31,3749.0,67.43,3833.0,70.18,3956.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-14 22:00:00,1,57.92,5605.0,69.13,5739.0,65.99,5847.0,64.56,5962.0,65.91,...,71.77,5745.0,81.98,6028.0,92.23,6211.0,86.57,6386.0,79.67,6563.0
2021-08-14 22:30:00,1,49.93,5492.0,57.92,5605.0,69.13,5739.0,65.99,5847.0,64.56,...,100.04,5508.0,71.77,5745.0,81.98,6028.0,92.23,6211.0,86.57,6386.0
2021-08-14 23:00:00,1,62.86,5344.0,49.93,5492.0,57.92,5605.0,69.13,5739.0,65.99,...,81.22,5319.0,100.04,5508.0,71.77,5745.0,81.98,6028.0,92.23,6211.0
2021-08-14 23:30:00,1,32.26,5204.0,62.86,5344.0,49.93,5492.0,57.92,5605.0,69.13,...,73.99,5364.0,81.22,5319.0,100.04,5508.0,71.77,5745.0,81.98,6028.0
2021-08-15 00:00:00,1,25.10,5268.0,32.26,5204.0,62.86,5344.0,49.93,5492.0,57.92,...,82.45,5356.0,73.99,5364.0,81.22,5319.0,100.04,5508.0,71.77,5745.0

In [12]:
# Transform dataframe to matrix
X = df.to_numpy()
y_price = y_price.to_numpy()
y_demand = y_demand.to_numpy()

## <font color = "brown"> Modelling </font>

In [13]:
# Normal equations
def NormalEquations(X, y):
    XtX = np.matmul(X.T, X)
    XtY = np.matmul(X.T, y)
    XtX_Inv = np.linalg.inv(XtX)
    
    b = np.matmul(XtX_Inv, XtY)
    
    return b

In [14]:
# Obtain parameter estimates for price
b_price = NormalEquations(X, y_price)

# Obtain parameter estimates for demand
b_demand = NormalEquations(X, y_demand)

## <font color = "brown"> Forecasting </font>

In [16]:
price_estimates = []
demand_estimates = []

for i in df.index:
    
    # Take a row of data and turn into numpy
    entry = df.loc[i].to_numpy()
    
    # Find estimate of price
    price_hat = np.dot(b_price, entry) # dot product
    price_estimates.append(price_hat)
    
    # Find estimate of demand
    demand_hat = np.dot(b_demand, entry) # dot product
    demand_estimates.append(demand_hat)

In [17]:
N = len(y_price)
p = len(df.columns)
# We already have X, y, and b

def SumOfSquares(y, X, b):

    # Just copying the formula
    SStot = np.matmul(y.T, y)
    SSreg = np.matmul(np.matmul(y.T, X), b)
    SSres = np.matmul((y - np.matmul(X, b)).T, (y - np.matmul(X, b)))
    
    return SStot, SSreg, SSres

In [18]:
def RSquared(SSres, SStot, y, n):
    
    R = 1 - SSres / (SStot - sum(y) ** 2 / n)
    return R

def MSE(SSres, n):
    
    M = SSres/n
    return M

def Fstat(SSreg, SSres, n, p):
    
    F = (SSreg / p) / (SSres / (n - p))
    return F

def Diagnostics(y, X, b, n, p):
    
    SStot, SSreg, SSres = SumOfSquares(y, X, b)
    
    R = RSquared(SSres, SStot, y, n)
    print(f"The R-squared is: {round(R, 2)}")
    
    M = MSE(SSres, n)
    print(f"The MSE is: {round(M, 2)}")
    
    F = Fstat(SSreg, SSres, n, p)
    print(f"The F-statistic is: {round(F, 2)}")

In [19]:
Diagnostics(y_price, X, b_price, N, p)
print()
Diagnostics(y_demand, X, b_demand, N, p)

The R-squared is: 0.66
The MSE is: 28262.74
The F-statistic is: 686.42

The R-squared is: 1.0
The MSE is: 3318.01
The F-statistic is: 2517997.46

In [20]:
PointsAhead = 2000
ExPostPrice = []
ExPostDemand = []

data = df.iloc[-1].to_list()
for i in range(PointsAhead):
    
    # Forecast new values given current predictors
    PredictPrice = np.dot(data, b_price)
    PredictDemand = np.dot(data, b_demand)

    data = data[:-2] # Remove last lag
    data.insert(1, PredictDemand) # Insert forecasted demand as predictor
    data.insert(1, PredictPrice) # Insert forecasted price as predictor
    
    # Store values in list
    ExPostPrice.append(PredictPrice)
    ExPostDemand.append(PredictDemand)